Nd pundit
SaraDawner2000/industrial-auth-1 pull request #2
Opened 2024-07-17 18:06 UTC by SaraDawner2000

Complete pundit assignments

2024-07-17 20:59 UTC, dylansarikas approved these changes
Looks good!

2024-07-17 20:59 UTC, dylansarikas commented on app/controllers/comments_controller.rb
Nice job getting rid of the extraneous lines of code!

2024-07-17 20:59 UTC, dylansarikas commented on app/policies/photo_policy.rb
nice job having new? call create? to reuse code

2024-07-22 02:24 UTC, ajmompr requested changes
Good start; see review comments

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/application_controller.rb
good

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action -> { authorize @comment || Comment }, except: [:new, :create]
good

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +    authorize @comment
redundant if we are calling before_action { authorize ...}

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +    authorize @comment
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action { authorize @follow_request || FollowRequest }
good

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action { authorize @photo || Photo }
good

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
>      @photo = Photo.new
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
redundant

2024-07-22 02:24 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action { authorize @user || User }
good

2024-07-22 02:24 UTC, ajmompr commented on app/policies/application_policy.rb
> +  attr_reader :user, :record
good use of pundit generator

2024-07-22 02:24 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == comment.author
not quite; we want to show all comments regardless if user is the comment author.

2024-07-22 02:24 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == comment.author
can be made more DRY

2024-07-22 02:24 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +    user == follow_request.sender ||
can be made more DRY

2024-07-22 02:24 UTC, ajmompr commented on app/policies/photo_policy.rb
+1

2024-07-22 02:24 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def liked?
don't need to worry about likes for this assignment since likes are not fully implemented across app

2024-07-22 02:24 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def show_photos?
good

2024-07-22 02:24 UTC, ajmompr commented on app/policies/user_policy.rb
refactor to be more DRY

2024-07-22 02:24 UTC, ajmompr commented on app/views/comments/_comment.html.erb
> +    <% if policy(comment).show? %>
we want to show all comments

2024-07-22 02:24 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
good

2024-07-22 16:30 UTC, SaraDawner2000 commented on app/views/comments/_comment.html.erb
> +    <% if policy(comment).show? %>
Why would we want to show a new comment submission form to users that are not authorized to comment on the particular photo? I believe this is a more elegant solution than telling the user he can't comment only after he tried via error message.

2024-07-22 16:36 UTC, SaraDawner2000 commented on app/policies/user_policy.rb
> +  def liked?
I was just making sure that each route has a policy for it, otherwise the verify_authorized after_action would bring this up

2024-07-22 16:39 UTC, SaraDawner2000 commented on app/policies/user_policy.rb
I refactored some of the routes, but I believe that for those methods that return true, directly returning true is shortrer than calling on another method to simply return true.

2024-07-22 16:58 UTC, SaraDawner2000 commented on app/controllers/comments_controller.rb
> +    authorize @comment
I removed the comments/new route all together because we don't use it in the app

2024-07-22 16:59 UTC, SaraDawner2000 commented on app/controllers/comments_controller.rb
> +    authorize @comment
This one isn't, because the policy checker breaks if the comment author isn't defined, so I call the policy checker after. I made an exception for this route in the exception

2024-07-22 17:04 UTC, SaraDawner2000 commented on app/controllers/photos_controller.rb
>      @photo = Photo.new
I refactored the before action to set the @photo variable to Photo.new if it isn't already set, which allowed me to delete the "new" action definition. Is this what you meant?

2024-07-22 17:11 UTC, SaraDawner2000 commented on app/policies/comment_policy.rb
> +    user == comment.author
technically, we don't need this view at all - comments should only be accessible under the posts they belong to. The DRY course of action would be to delete both the route and the policy for it. My logic was that if someone were to view a comment out of context, it would be the author, but I changed the policy to return "true"

2024-07-22 17:14 UTC, SaraDawner2000 commented on app/controllers/photos_controller.rb
> +    authorize @photo
I didn't push the latest commit that had these removed--
it should be clean now

2024-07-22 17:14 UTC, SaraDawner2000 commented on app/controllers/photos_controller.rb
> +    authorize @photo
same as above

2024-07-22 19:44 UTC, ajmompr approved these changes
Good job!

2024-07-22 19:45 UTC, merged